name: Generate Currently Working On

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate current_work.svg
        run: |
          mkdir -p dist
          CURRENT_MESSAGE="Building automated CI/CD pipeline 🚀"
          cat <<-'EOF' > dist/current_work.svg
          <svg width="600" height="100" xmlns="http://www.w3.org/2000/svg">
            <rect width="600" height="100" fill="#1E1E1E" />
            <text x="300" y="55" font-size="24" text-anchor="middle" fill="#61dafb" font-family="monospace">
              Currently working on: ${CURRENT_MESSAGE}
            </text>
          </svg>
          EOF

      - name: push current_work.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
